server:
  port: ${PORT:9292}
spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3346/mysql_image?useSSL=false&allowPublicKeyR etrieval=true
    driverClassName: com.mysql.jdbc.Driver
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      ddl-auto: update
    show-sql: 'true'