create table ASSOCIATE_TB(
ID_ASSOCIATE bigint(50) NOT NULL AUTO_INCREMENT,
NAME   varchar(60) NOT NULL,
CPF    varchar(100) NOT NULL,
STATUS			varchar(15),
DT_REGISTER  TIMESTAMP,
DT_UPDATE  TIMESTAMP,
PRIMARY KEY (`ID_ASSOCIATE`));