create table NEW_SUBJECT_VOTING_TB(
ID_NEW_SUBJECT_VOTING bigint(50) NOT NULL AUTO_INCREMENT,
ID_SUBJECT   bigint(60) NOT NULL,
DT_REGISTER  TIMESTAMP,
DT_END  TIMESTAMP,
PRIMARY KEY (`ID_NEW_SUBJECT_VOTING`));