create table START_VOTING_TB(
ID_START_VOTING bigint(50) NOT NULL AUTO_INCREMENT,
ID_SCHEDULE   bigint(60) NOT NULL,
ASSOCIATE_IDS   bigint(60) NOT NULL,
TITLE_SCHEDULE   varchar(200) NOT NULL,
STATUS			varchar(15),
DT_START_VOTING  TIMESTAMP,
PRIMARY KEY (`ID_START_VOTING`));