create table SUBJECT_TB(
ID_SUBJECT bigint(50) NOT NULL AUTO_INCREMENT,
SUBJECT   varchar(60) NOT NULL,
DESCRIPTION   varchar(2000) NOT NULL,
STATUS			varchar(15),
STATUS_VOTE		varchar(15),
DT_REGISTER  TIMESTAMP,
DT_UPDATE  TIMESTAMP,
PRIMARY KEY (`ID_SUBJECT`));