create table VOTE(
ID_VOTE bigint(50) NOT NULL AUTO_INCREMENT,
ID_SUBJECT   bigint(60) NOT NULL,
VOTE            VARCHAR(60) NOT NULL,
DT_REGISTER  TIMESTAMP,
DT_END   TIMESTAMP,
PRIMARY KEY (`ID_START_VOTING`));